# Weyl Algebra

:::{.definition name="Weyl algebra"}
The Weyl algebra $W_p$ and one site is finitely generated by 
$U_{(p)}, V_{(p)}$, subject to 
\[ 
    U^p = V^p = 1, \quad VU = \omega UV 
\] 
It generates the Schwinger basis indexed by 
$\xi = (q, p) \in \mbb Z^p\times \mbb Z^p$: 
\[ 
    J_\xi = \bar \omega^{\xi_1\xi_2/2} V^{q} U^p
\] 
The $N$-site Weyl algebra is defined by $W_p(N)=W_P^{\ot n}$. 
:::

For example, for $p=2$ we obtain the Pauli basis 
$V=\sigma_x, U=\sigma_z$. 

:::{.proposition name="Weyl Lie relation"}
Let $\xi=(q, p)$ equipped with addition modulo $p$ and 
$\xi_1\times \xi_2 = q_1p_2 - q_2p_1$, then 
\[ 
    [J_{\xi_1}, J_{\xi_2}] = 2i \sin \left(
        \df \pi p \xi_1\times \xi_2 
    \right) J_{\xi_1+\xi_2}
\] 
:::

Proceeding to compute the commutator, note that $UV = \bar \omega VU$, then 
\begin{align}
    [J_{\xi_1}, J_{\xi_2}] 
    &= [\bar \omega^{q_1p_1/2} V^{q_1} U^{p_1},
    \bar \omega^{q_2 p_2/2} V^{q_2} U^{p_2}] \\ 
    &= \omega^{-\frac 1 2 (q_1p_1 + q_2 p_2)} 
    (V^{q_1} U^{p_1} V^{q_2} U^{p_2} - V^{q_2} U^{p_2}V^{q_1} U^{p_1}) \\ 
    &= \omega^{-\frac 1 2 (q_1p_1 + q_2 p_2)} 
    V^{q_1 + q_2} U^{p_1 + p_2} (\omega^{-p_1 q_2} - \omega^{-q_1p_2}) 
    (\#eq:commWeyl)
\end{align}
On the other hand, reminding that $\xi_1\times \xi_2 = q_1p_2 - q_2p_1$, we obtain 
\begin{align}
    2i \sin \left(\df \pi p \xi_1\times \xi_2 \right) J_{\xi_1+\xi_2} 
    &= \left[\exp\left(\df{i\pi}{p} \xi_1\times \xi_2\right) 
    - \exp\left(-\df{i\pi}{p} \xi_1\times \xi_2\right)\right] 
    \omega^{-\frac 1 2 (q_1+q_2)(p_1+p_2)} V^{q_1+q_2}U^{p_1+p_2} \\ 
    &= \left(\omega^{\xi_1\times \xi_2/2} - \omega^{-\xi_1\times \xi_2/2}\right)
    \omega^{-\frac 1 2 (q_1+q_2)(p_1+p_2)}V^{q_1+q_2} U^{p_1+p_2}
\end{align}
In the first term $\omega^{\xi_1\times \xi_2/2}$, the $+q_1p_2$ cancels with 
that from $\omega^{-\frac 1 2 (q_1+q_2)(p_1+p_2)}$, leaving 
$\omega^{-\frac 1 2 (q_1p_q + q_2p_2) - q_2p_1}$, matching 
the first term in \@ref(eq:commWeyl), as desired. The same goes for the second term. 


:::{.proposition name="canonical decomposition of Weyl algebras"}
Let $p=p_1p_2$ relative primes, then 
\[ 
    W_{p_1}\ot W_{p_2} \cong W_p 
\] 
under the mapping extended multiplicatively from the generators 
\[ 
    \varphi\, U_{(p_1)} \ot U_{(p_2)} = U_{(p)}, \quad 
    \varphi\, V_{(p_1)} \ot V_{(p_2)} = V_{(p)}^{(p_1+p_2)}
\] 
Note that since $p_1, p_2$ are relative primes, $U\ot U$ and 
$V\ot V$ does generate $W_{p_1}\ot W_{p_2}$. 
Explicitly, we obtain the embedding isomorphisms 
\begin{align}
    \varphi \, U^{p_2}_{(p_1)} \ot U^{p_2}_{(p_2)} 
    &= \varphi \, U^{p_2}_{(p_1)} \ot 1 = U_{(p)}^{p_2} \\ 
    \varphi \, V^{p_2}_{(p_1)} \ot V^{p_2}_{(p_2)} 
    &= \varphi \, V^{p_2}_{(p_1)} \ot 1 = V_{(p)}^{(p_1+p_2)p_2}
    = V_{(p)}^{p_2^2}
\end{align}
:::

## Weyl parafermions {-}

:::{.definition name="Weyl parafermion generators"}
Fixing $p$ and $N$, we can define an alternate set of generators of $W_p(N)$ by 
\[ 
    \Gamma_j = U_1\dots U_{j-1}V_j, \quad 
    \Delta_j = U_1\dots U_{j-1} (U_j V_j) = \Gamma_j U_j 
\] 
Set $\gamma_1, \dots \gamma_{2n} = \Gamma_1, \Delta_1, \Gamma_2, \Delta_2, \dots$, 
then we obtain 
\[ 
    \gamma_j \gamma_k = [\delta_{jk} + (1-\delta_{jk}) \omega]  \gamma_k \gamma_j, \quad 
    \Gamma_j^p = \Delta_j^p = 1, \quad \gamma_j^\dag = \gamma_j^{p-1}
\] 
One can recover the Weyl generators by 
\[ 
    U_j = \Gamma_j^\dag \Delta_j, \quad 
    V_j = \Gamma_j \prod_{k=1}^{j-1} U_k^\dag
    = \Gamma_j \prod_{k=1}^{j-1} \Delta_k^\dag \Gamma_k 
\] 
:::

For the case of $p=2$, we obtain $\Gamma_j = Z_1\dots Z_{j-1}X_j$ and 
$\Delta_j = -iZ_1 \dots Z_{j-1}Y_j$. 

For a more comprehensive treatment of duality, see [@cobanera2011bond]. 

:::{.definition name="parafermion self-duality"}
We are interested in the following duality for the 
$p$-clock model (which has a transparant parafermion interpretation). 
Fixing $N$ sites, consider the von-Neumann algebra $\mca A$ generated by 
$\{U_1, \dots, U_n, V_1V_2^\dag, V_2V_3^\dag, \dots, V_{N-1}V_N^\dag, V_N\}$. 
Let $r(j_{1\leq j\leq N}) = N+1-j$ (denoting the reverse order) and define 
\begin{align}
    \Phi_d(U_1) 
    &= V^\dag_N, \quad \Phi_d(V_N) = U_1 \\ 
    \Phi_d(U_j) &= V^\dag_{r(j)} V_{r(j)+1}, \quad 
    \Phi_d(V_j V_{j+1}^\dag) = U_{r(j)}
\end{align}
:::

:::{.definition name="Artin braid group"}
The braid group $B_L$ on $L$ modes is the free group in generators 
$\sigma_1, \dots, \sigma_{L-1}$ subject to 
$\sigma_k \sigma_{k+1}\sigma_k = \sigma_{k+1}\sigma_k \sigma_{k+1}$ 
and $\sigma_k\sigma_l = \sigma_l\sigma_k$ if $|k-l|\geq 2$. 
:::

## Fock parafermions {-}

Here, we construct the Fock space of indistinguishable particles upon specifying: 

1. The state space $\mca H$ of a single particle (orbitals it can occupy). 
2. A rule to multiply $N$ single-particle states to generate a $N$-body state 
    with the correct exchange and exclusion statistics. 

Let $n_E\geq 2$ denote the exclusion parameter, 
the Fock space $\mca F$ on $M$ sites is 
\[ 
    \mca F = \bigoplus_{N=0} \text{span of } 
    |n_1, \dots, n_M\ra \text{ subject to } \sum_{r=1}^M n_r = N
\] 
We abbreviate the notation $|n_j\ra$ denotes $n_j$ particles in the 
$j$-th entry, and $|n_j, n_k\ra$ with $(n_j, n_k)$ particles in the 
$(j, k)$-th sites, and so on. We next proceed to make $\mca F$ an algebra 
by specifying multiplication: 

:::{.proposition name="multiplication on Fock space"}
Define $|1_j\ra=|n_j=1\ra$ and the following rules for multiplication: 

1. $|1_{\forall j}\ra^{n_E} = 0$, where $n_E$ is the exclusion parameter. 
2. $|n_1, \dots n_M\ra = |1_1\ra^{n_1} |1_2\ra^{n_2} \dots |1_M\ra^{n_M}$.
3. $|1_j\ra|1_{k\neq j}\ra = \omega |1_k\ra|1_j\ra\implies 
|n_j\ra|n_k\ra = \omega^{n_kn_j} |n_k\ra|n_j\ra = |n_j, n_k\ra$ for $j\leq k$.  
4. Every operator commuting with every other operator in $\mca F$ is a scalar 
    multiple of the Fock vacuum. 
:::


:::{.definition name="creation and annihilation operators"}
Define the creation operator $C_j^\dag: \mca F\to \mca F$ by extending 
\[ 
    C_j^\dag |n_1, \dots, n_M\ra = |1_j\ra |n_1, \dots, n_M\ra
    = \omega^{\sum_{k=1}^{j-1} n_k} |n_1, \dots, n_j+1, \dots, n_M\ra
\] 
In lieu of the given inner product, 
its adjoint annihilation operator $C_j$ is 
\begin{align}
    \la m_1, \dots, m_M| (C_j |n_1, \dots, n_M\ra) 
    &= (C_j^\dag |m_1, \dots m_M\ra)^\dag |n_1, \dots, n_M\ra \\ 
    &= \omega^{\sum_{k=1}^{j-1} m_k} \la m_1, \dots, m_j+1, m_M| n_1, \dots, n_M\ra \\
    &= \omega^{\sum_{k=1}^{j-1} n_k} \delta_{m_1n_1}\dots \delta_{(m_j+1)n_j} \dots \delta_{m_M n_M} \\ 
    &= \omega^{\sum_{k=1}^{j-1} n_k}\delta_{m_1n_1}\dots \delta_{m_j(n_j-1)} \dots \delta_{m_M n_M} \\ 
    C_j |n_1, \dots, n_M\ra
    &= \omega^{\sum_{k=1}^{j-1} n_k}|n_1, \dots, n_j-1, n_M\ra 
\end{align}
The algebra of the creation and annihilation operators thus are 
\begin{align}
    C_j^{\dag p} 
    &= C_j^p = 0, \quad C_j^\dag C_{k>j}^\dag = \omega C_k^\dag C_j^\dag, \quad 
    C_j C_k = \omega C_k C_j
\end{align}
:::

## Canonical transforms {-}

Recalling the Pf majorana algebra: 
\[ 
    \gamma_j^p = 1, \quad \gamma_j^\dag = \gamma_j^{p-1}, \quad 
    \gamma_j \gamma_k = \omega^{s_{jk}} \gamma_k \gamma_j, \quad 
    s_{jk} = \begin{cases}
        1 & j < k \\ 
        -1 & j>k \\ 
        0 & j = k
    \end{cases}
\] 
For the case $p=2$, consider the unitary mapping ansatz 
$\varphi\, \gamma_j = A_{jk}\gamma_k$, 
we have the following equations: 
\begin{align}
    1 &= (\varphi\, \gamma_j)^2 
    = A_{ja} A_{jb} \gamma_a \gamma_b 
    = (A^TA)_{ab} \gamma_a \gamma_b \implies A^TA = I \\ 
    A_{jk}^* \gamma_j 
    &= A_{jk} \gamma_j \implies A_{jk}\in \R \\ 
    (\varphi\, \gamma_j)(\varphi\, \gamma_k) 
    &= \omega^{s_{jk}} (\varphi\, \gamma_k)(\varphi\, \gamma_j) 
    \implies TODO
\end{align}

## Low-dimensional Lie algebras {-}

Focusing on the $p=3$ case, let 
$\omega = \exp \left(2\pi i/3\right)$ 
and label the majorana operators $\gamma_1, \dots, \gamma_{2n}$ as usual, 
subject to the algebraic relations 
\[ 
    \gamma_j^3 = 1, \quad \gamma_j^\dag = \gamma_j^2, \quad 
    \gamma_j \gamma_k = \omega^{s_{jk}} \gamma_k \gamma_j, \quad 
    s_{jk} = \begin{cases}
        1 & j < k \\ 
        -1 & j>k \\ 
        0 & j = k
    \end{cases}
\] 
Consider operators $\Gamma_{jk} = \gamma_j \gamma_k^2$. 
First note that operators of the form $\Gamma_{jk} + \Gamma_{kj}$ 
is Hermitian: 
\[ 
    \Gamma_{jk}^\dag 
    = \gamma_k^{2\dag}\gamma_j^\dag 
    = \gamma_k \gamma_j^2 = \Gamma_{kj}
\] 
Next compute the commutator brackets: for $j, k, l$ distinct, we obtain 
\begin{align}
    [\Gamma_{jk}, \Gamma_{kl}] 
    &= \gamma_j \gamma_k^2 \gamma_k \gamma_l^2 - 
    \gamma_k \gamma_l^2 \gamma_j \gamma_k^2  
    = (1 - \omega^{2s_{kl} + s_{kj} + 2s_{lj}}) \Gamma_{jl}
\end{align}