# Covering theory

This section recounts the theory of universal 
covers for "nice" topological spaces. 

In particular, we aim to understand (and program) how the 
fundamental groups of closed hyperbolic $3$-manifolds can be 
represented by matrix subgroups of the isometry group of $\mbb H^3$, 
and how such representations can be visualized as "lattice tilings" of $\mbb H^3$. 

1. Review the basics of covering theory. 
2. We revisit the proof of the Švarc–Milnor lemma (Loh, 5.4), which 
    gives an explicit construction of the <u>quasi-isometric embedding 
    of the Cayley graph of a fundamental group into the 
    universal cover. </u>

To obtain the quasi-isometry constants of the embedding 
$\Delta(\pi_1(\text{Weeks manifold}), \{a, b\})$, we: 

1. Compute the generating set $S$ of $\pi_1(\text{Weeks manifold})$ according to 
    the Švarc–Milnor lemma. 
2. Compute the quasi-isometry constants of the embedding 
    $\Delta(\pi_1(\text{Weeks manifold}), S)$. 
3. Use the fact that $\Delta(\pi_1(\text{Weeks manifold}), \{a, b\})$ 
    is quasi-isometric to $\Delta(\pi_1(\text{Weeks manifold}), S)$. 

## Topological preliminaries {-}

See Loh (A.1.2) and Munkres for more details. Here 
we recount the basics of covering theory. 

- Every "nice" topological space has a universal cover $\widetilde X$ which is simply connected. 
- The space $\widetilde X$ admits a free, properly discontinuous group action of $\pi_1(X, x_0)$. 
    - There is a homeomorphism from $\widetilde X$ modulo $\pi_1(X, x_0)$ to $X$ by sending $x_0$ 
    to the class of $\widetilde x_0$. In a sense $X$ is a "representative pancake" in $\widetilde X$. 
- If $X$ is a metric space, then $\widetilde X$ carries the induced path-metric and the action 
    of $\pi_1(X, x_0)$ is isometric, so <u>fundamental groups are subgroups of the isometry group 
    of the universal cover</u>. 

Some more results about hyperbolic spaces: 

1. Using the hyperboloid model of $\mbb H^3$ as the $x_0>0$ slice of $\mbb R^4$ 
    under the contour equation $-x_0^2 + x_1^2 + x_2^2 + x_3^2 = 1$, we obtain 
    \[ 
        \mrm{Isom}\, \mbb H^3 = O^+(3, 1)
    \] 
    where $O^+(3, 1)$ is the group of proper orthochronous 
    Lorentz transformations which keep the upper-sheet 
    of the hyperboloid invariant. 
2. A standard result has $\mrm{SO}^+(3, 1)\cong \mrm{PSL}(2, \mbb C)$, i.e. there is a 
    $2$-to-$1$ covering $\mrm{SL}(2, \C)\to \mrm{SO}^+(3, 1)$. 
3. **Need to double-check:** for orientable closed manifolds (e.g. the Weeks manifold?), 
    the deck transformations are orientation-preserving, so 
    $\pi_1(\text{Weeks manifold}) \subset \mrm{SO}^+(3, 1)$. 

## Švarc–Milnor lemma {-}

:::{.theorem #svarcMilnor name="Švarc–Milnor lemma"}
Given the group action of $G$ on a non-empty metric space 
$(X, d)$ such that $\forall g: x\mapsto g\cdot x$ is an isometry. 
Further suppose that $X$ is $(c, b)$-quasi-geodesic and that 
there is a subset $B\subset X$ such that: 

1. $\mrm{diam}\, B$ is finite. 
2. The $G$-translates of $B$ cover $X$ (not necessarily disjoint). 
3. Let $B'$ be the $2b$-thickening of $B$, the set 
    $S = \{g\in G \, | \, g\cdot B'\cap B'\neq \emptyset\}$ is finite. 
    - The generating set $S$ is geometrically the **neighboring set** 
    which sends the thickenedfundamental domain $B'$ to overlapping neighboring translations. 

Then the following holds: 

1. $G$ is finitely generated by $S$. 
2. Fixing any basepoint $x\in X$, the Cayley graph of $G$   
    is quasi-isometric to $X$ by the map 
\[ 
    G\xrightarrow {g\mapsto g\cdot x} X
\] 
3. In particular, we obtain the following quasi-isometric bound: 
\[ 
    \df b {c^2} d_S(e, g) - b \left(\df 1 {c^2} - 1\right) 
    \leq d(x, g\cdot x) \leq 2(\mrm{diam}\, B + 2b) \cdot d_S(e, g)
    (\#eq:SMquasiIsometricBound)
\] 
:::
_Proof:_ The proof proceeds as follows: 

1. Proving that $S$ generates $G$: given $g\in G$, connect $x, g\cdot x$ 
    by a quasi-geodesic, then divide the geodesic into sufficiently fine intervals 
    with endpoints covered by $g_j$ such that $g_{j-1}\cdot B'\cap g_j\cdot B'$ 
    is nonempty, so that $g_{j-1}^{-1}g_j$ is in the neighboring set. 
2. Proving that $g\mapsto g\cdot x$ is a quasi-dense: follows from the tiling of 
    $X$ by $G$-translates of $B$. 
3. Proving that $g\mapsto g\cdot x$ is a quasi-isometric embedding: 
    - Use the lower bound provided by the quasi-geodesicity. 
    - Upper-bound using the fact that subsequent endpoints $(x_j)$ cannot be 
    too far apart. 

Fix $g\in G$ for which we wish to show that $g\in \la S\ra_G$. 
Choose any $x\in B$ and construct a $(c, b)$-quasi-geodesic 
$\gamma:[0, L]\to X$ connecting $x$ and ending in $g\cdot x$. 

- Divide up the interval $[0, L]$ into sufficiently fine 
    intervals such that $x_0=x, x_n=g\cdot x$, and that 
    $d(x_{j-1}, x_j) \leq c\cdot |t_{j-1}-t_j|_{\leq b/c} + b \leq 2b$. 

We proceed to show that $\forall j\in \{1, \dots, n\}$, 
\[ 
s_j = g_{j-1}^{-1} g_j \in S = \{g\in G \, | \, g\cdot B'\cap B'\neq \emptyset\}
\] 
To show this, $x_j\in B_{2b}(g_{j-1}\cdot B) = g_{j-1}\cdot B_{2b}(B) = g_{j-1}\cdot B'$. 
Similarly, $x_j\in g_j\cdot B\subset g_j\cdot B'$ so $g_{j-1}\cdot B'\cap g_j\cdot B' \supset \{x_j\}$ 
and $s_j=g_{j-1}^{-1}\cdot g_j\in S$. Then 
\[ 
    g = g_n = g_{n-1} g_{n-1}^{-1} g_n = g_{n-1}s_n = g_{n-2}s_{n-1}s_n = \cdots = s_1\cdots s_n \in \la S\ra 
\] 
To show that $\varphi:g\mapsto g\cdot x$ is quasi-dense, 
simply note that the quasi-dense constant is bounded by $\mrm{diam}\, B$ since the 
$g$-translates of $B$ cover $X$. 
To next show that $\varphi$ is a quasi-isometric embedding, using the 
isometric condition $g(\varphi\, g, \varphi\, h) = d(e, \varphi(g^{-1}h))$ 
and $d_S(g, h) = d_S(e, g^{-1}h)$ we obtain 

1. Lower bound $d(x, g\cdot x)$ in terms of $d_S(e, g)$: 
    let $\gamma$ be a quasi-geodesic from $x$ to $g\cdot x$ as in the first part, then 
    noting that $d_S(e, g) \leq n$ (since $g=s_1\dots s_n$) we obtain 
\begin{align*}
    d(x, g\cdot x) 
    &= d(\gamma_0, \gamma_L) 
    \geq \df 1 c L - b \geq \df 1 c \cdot \df{b}{c}(n-1) - b \\ 
    &= \df{b}{c^2} \cdot n - \df{b}{c^2} - b 
    \geq \df b {c^2}d_S(e, g) - \df{b}{c^2} - b
\end{align*}
2. Upper bound of $d(x, g\cdot x)$ in terms of $d_S(e, g)$: 
    let $d_S(e, g)=n$ so that $g=s_1\dots s_n$ with $s_j\in S\cup S^{-1}$. 
    Then using the triangle inequality, the isometric condition $d(g\cdot x, g\cdot y)=d(x, y)$, 
    we obtain 
\begin{align*}
    d(x, g\cdot x) 
    &\leq d(x, s_1\cdot x) + d(s_1\cdot x, s_1\cdot s_2\cdot x) + \cdots +
    d(s_1\cdots s_{n-1}\cdot x, s_1\cdots s_n\cdot x) \\
    &= d(x, s_1\cdot x) + d(x, s_2\cdot x) + \dots + d(x, s_n\cdot x) \\ 
    &\leq n\cdot 2(\mrm{diam}\, B + 2b) \leq 2(\mrm{diam}\, B + 2b) \cdot d_S(e, g)
\end{align*}
In the last line we used the fact that $\forall x, s\in S = \{g\in G \, | \, g\cdot B'\cap B'\neq \emptyset\}$, 
we have $d(x, s\cdot x) \leq 2(\mrm{diam}\, B + 2b)$: let $y\in s\cdot B'\cap B'$, then 
\[ 
    d(x, s\cdot x) \leq d(x, y) + d(y, s\cdot x) 
    \leq (\mrm{diam}\, B + 2b) + (\mrm{diam}\, B + 2b)
\] 

:::{.corollary #svarcMilnorRiemann name="fundamental groups and universal covers"}
Given a compact, boundaryless Riemannian manifold $M$ with universal cover $\widetilde M$, 
the fundamental group $\pi_1(M)$ is finitely-generated and for every basepoint 
$x\in \widetilde M$, the map 
\[ 
    \pi_1(M)\xrightarrow {g\mapsto g\cdot x} \widetilde M 
\] 
given by the action of the fundamental group on $\widetilde M$ by deck transformations 
(analogous to reshuffling pancakes) is a quasi-isometry with bound 
\[ 
    b \cdot d_S(e, g) \leq d(x, g\cdot x) \leq 2(\mrm{diam}\, B + 2b) \cdot d_S(e, g)
    (\#eq:CoverQuasiIsometricBound)
\] 
<u> Note that varying $b$ will vary the generating set </u> S. 
:::
_Proof:_ The action of deck transformations for closed Riemannian manifolds is isometric, 
proper, and cocompact. Also note that $\widetilde M$ is 
$(1, b)$-quasi-geodesic for every $b\in \R_{>0}$. 
Given such action, we simply choose $B=M$ in theorem \@ref(thm:svarcMilnor). 
To obtain the claimed bound, substitute $c=1$ in \@ref(eq:SMquasiIsometricBound). 