---
title: "MERA Learning Material"
author: "Nicholas Lyu"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [refs.bib]
biblio-style: "numeric"
split_bib: yes
link-citations: true
---

\usepackage{cancel}
\usepackage{amsmath}
\usepackage{bm}
\newcommand{\pd}[1]{\partial_{#1}}

\newcommand{\mbb}{\mathbb}
\newcommand{\mbf}{\mathbf}
\newcommand{\mb}{\boldsymbol}
\newcommand{\mrm}{\mathrm}
\newcommand{\mca}{\mathcal}
\newcommand{\mfk}{\mathfrak}
\newcommand{\tr}{\mrm{tr}} 
\newcommand{\df}{\dfrac}
\newcommand{\la}{\langle}
\newcommand{\ra}{\rangle}
\newcommand{\dag}{\dagger}

\newcommand{\Cl}{\mca C}
\newcommand{\Gr}{\mca G}
\newcommand{\Pf}{\mrm{Pf}}
\newcommand{\Pa}{\mca P}
\newcommand{\R}{\mbb R}
\newcommand{\C}{\mbb C}
\newcommand{\N}{\mbb N}
\newcommand{\F}{\mbb F}
\newcommand{\supp}{\mrm{supp}}

\newcommand{\poly}{\mrm{poly}}
\newcommand{\ot}{\otimes}

# Research agenda 

In this project, we aim to construct a tensor-network ansatz 
for CFT ground states on $S^2$. Such an ansatz will help understand 
$AdS_3$ gravity by the holography conjecture. 

1. Identify "nice" groups with Gromov boundary $S^2$. 
2. Construct their Cayley graphs out to a fixed radius, 
    embedding endpoints on $S^2$. 
3. Investigate the minimal-surface property of the Cayley graphs 
    (at least an upper-bound). 
4. Explicitly construct the higher-dimensional generalization 
    of HTN [@evenbly2017hyperinvariant], and numerical implementations. 

## Progress log {-}

Main takeaways so far: 

1. $\partial \mbb H^3\cong S^2$, and quasi-isometric metric spaces have 
    the same Gromov boundary, so it suffices to find groups which are 
    quasi-isometric to $\mbb H^3$. 
2. By the Svarc-Milnor lemma (Corollary 5.4.13 in [@loh2017geometric]), 
    the fundamental groups of closed hyperbolic 3-manifolds have Gromov boundary $S^2$. 

Examples of groups with $S^2$ Gromov boundary (from Regina): 

- m003(-3, 1): $\la a, b| a^2b^2a^2b^{-1}ab^{-1}, a^2b^2a^{-1}ba^{-1}b^2\ra$. 
- m003(-2, 3): $\la a, b|a^{-1}b^{-1}aba^{-1}bab^{-1}a^{-1}b^2, ab^{-1}a^{-1}baba^{-1}b^{-1}ab^3\ra$. 
- m003(-4, 3): $\la a, b|a^2bab^{-2}ab, a^2b^2a^{-1}ba^{-1}b^2\ra$. 
- m003(-4, 1): $\la a, b|a^{-3}b^2abab^2, aba^3b^{-2}a^3b\ra$. 

The geometric group theory perspective led to tilings of $\mbb H^3$, 
and our project should directly generalize the hyperbolic tensor network construction. 

### Jan 16: the word problem for candidate groups {-}

See section 3 for more details on (1-4) below. 
The approach in (5) is in progress in section 4. 

1. <u>We have identified a class of hyperbolic groups with Gromov boundary $S^2$</u>, 
    corresponding to the fundamental groups of closed hyperbolic $3$-manifolds. 
    - We obtained a "census" of this set of groups from Regina's database. 
    - Additionally, the database sorted the stored groups by the hyperbolic volume 
    of its corresponding manifold, which roughly concurs with the simplicity of the presentation 
    (number of generators, and length of the relations). 
2. There seems to be no established technology for 
    <u>constructing the Cayley graphs</u> of such groups (up to a certain radius). 
    - Mathematica supports plotting Cayley graphs but only for finite-order groups. 
3. Computing the Cayley graphs requires <u>solving the word problem</u>.  
4. My first attempt has been understanding and implementing the Dehn algorithm, 
    which yields a linear-time algorithm for solving the word problem. 
    - After carefully reading the proof (in hopes of understanding the algorithm), 
    I found that the Dehn algorithm is quite computationally infeasible. 
    Computing the Dehn presentation has exponential complexity in the hyperbolic constant, 
    which is likely exponentially-intractible as well. 
5. I'm investigating aother approach to solving the word problem: 
    by representing the fundamental group as subgroups of the isometry group of 
    the universal cover $\mbb H^3$ (which should be the group of Mobius transforms, 
    which admit a convenient matrix representation?). 
    I intend to proceed by the following: 
    - Understand the isomorphism between fundamental groups and deck transformations. 
    - Understand the embedding of deck transformations into the isometry 
    group of the universal cover. 
    - Understand the matrix representation of the isometry group of $\mbb H^2$. 
    - Compute the matrix representations of select hyperbolic groups, solve the 
    word problem, and write a program to compute the Cayley graphs. 

The resulting Cayley graph may not have neat tree-like structure. 
There is a chance that in order to understand which edges should correspond to 
the lattice sites (and to compute the size of a boundary patch), 
I may also need to dig into the construction of the quasi-isometry 
between the $\pi_1$ of closed hyperbolic $3$-manifolds and $\mbb H^3$. 

### Jan 26: Visualizing the Cayley graph of the Weeks manifold {-}

1. I found the holonomy representation of the fundamental group of the 
    Weeks manifold as a subgroup of $O(3, 1)$, after tampering with SnapPy a bit. 
    - With this faithful representation in hand, we can compute the Cayley graph 
    efficiently, up to floating-point errors. 
2. On the theoretical side, I delved into the Svarc-Milnor lemma, 
    which gives the explicit construction of the quasi-isometry between (1) the Cayley 
    graph of a fundamental group of a manifold, and (2) the universal cover of the manifold. 
    - I believe that the quasi-isometric embedding given by this lemma is the one we need 
    to "visualize" the Cayley graph as a discrete tiling of $\mbb H^3$. 
    - In particular, <u>the vertices of the image of the Cayley graph under this embedding 
    are simply the image of an arbitrary basepoint (e.g. the "center" of $\mbb H^3$) 
    under the corresponding deck transformations</u>. 
    - With the matrix representation of the fundamental group in hand, we can compute 
    the image of the basepoint under the matrix representation in the hyperboloid model, 
    then change to the familiar Poincaré disk (ball) model to visualize the Cayley graph in 3D. 
    - Theoretically, we can also explicitly compute the 
    quasi-isometric constants for the particular case of the Weeks manifold. 
3. I have made some numerical progress in computing the Cayley graph, but a very 
    rudimentary implementation of visualizing it did not yield the neat, desired "tiling" 
    of the Poincaré ball. 
    - This may be a bug in implementation, 
    or something more fundamental (e.g. the Svarc-Milnor quasi-isometry does not guarantee a neat "tiling"
    in the visual sense). 


### Feb 5: The Weeks tiling (finally) {-}

New results are documented in Section 5. Summary: 

1. With disentanglers, the 1D MERA graph is indeed quasi-isometric to $\mbb H^2$. 
2. The 2D MERA graph is **locally quasi-isometric** to $\mbb H^2$, but <u>not globally so</u>. 
    This highlights the special dimensionality. 
    - In 1D, the $\mbb R^1$ MERA nicely wraps around $S^1$ by a covering map, 
    under which translational symmetry maps onto the rotational symmetry of $S^1$ by boundary 
    conditions. 
    - In 2D, there is no analogous periodic boundary condition which wraps a lattice on $\mbb R^2$ 
    onto $S^2$. 
        - There is no covering map $\mbb R^2\to S^2$ since $S^2$ is simply connected. 
        - I believe there're results which rule out self-similar lattices on $S^2$. 
    - This verifies our intuition that <span style="color: blue"> 
    1D MERA is quasi-isometric to $\mbb H^2$, but the 2D MERA 
    is not quasi-isometric to $\mbb H^3$ </span>. 
3. I constructed the Svarc-Milnor quasi-isometry for a Cayley graph of the Weeks manifold group. 
    - A key realization is that the resulting graph essentially represents 
    a <u>regular tiling</u> of $\mbb H^3$. 
4. Using the tiling property, I refined the area-law argument 
    for our construction (hypothesis \@ref(hyp:hAreaLaw)). 

Some questions: 

1. After recognizing the tiling property, I realized that our construction seems 
    very similar to hyperbolic-invariant MERA (hyMERA), [@evenbly2017hyperinvariant]. 
    - HyMERA takes a tiling of $\mbb H^2$ and constructs the TN graph 
    by placing vertices at the extremal points of the tiles, and edges connecting the vertices 
    (effective "tracing out" the tiling). 
    - Our construction place vertices at the center of the tiles, and edges 
    connecting the vertices denoting neighboring tiles. 
2. <span style="color: blue"> The tiling property seems "more fundamental" </span> 
    to our arguments, and it may be more general (I'm looking more into this). 
2. There is a corresponding hyMERA construction for the Weeks manifold. 
    The only differences seem to be: 
    - All the tensors in our construction have the same rank. 
    while in the hyMERA construction, the rank vary depending on the vertex. 
    - The tensors in our construction have high rank (equal to the number of faces in the domain) 
    compared to hyMERA, whose rank is bounded by maximum degree of a vertex in the tiling. 
3. The original hyMERA paper provides many future directions, e.g. finding 
    an efficient optimization algorithm for the tensors. 